// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_app from "./routes/_app.tsx";
import * as $api_claim_status from "./routes/api/claim-status.ts";
import * as $api_claim from "./routes/api/claim.ts";
import * as $api_ethos_score from "./routes/api/ethos-score.ts";
import * as $api_ethos_users from "./routes/api/ethos-users.ts";
import * as $api_search_users from "./routes/api/search-users.ts";
import * as $api_sync_whitelist from "./routes/api/sync-whitelist.ts";
import * as $api_transfers from "./routes/api/transfers.ts";
import * as $api_vouched_users from "./routes/api/vouched-users.ts";
import * as $index from "./routes/index.tsx";
import * as $ClaimReward from "./islands/ClaimReward.tsx";
import * as $ConnectWallet from "./islands/ConnectWallet.tsx";
import * as $EthosStatus from "./islands/EthosStatus.tsx";
import * as $Header from "./islands/Header.tsx";
import * as $HomePage from "./islands/HomePage.tsx";
import * as $SendTokens from "./islands/SendTokens.tsx";
import * as $TransactionLog from "./islands/TransactionLog.tsx";
import * as $VouchedUsers from "./islands/VouchedUsers.tsx";
import * as $WalletBalance from "./islands/WalletBalance.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_app.tsx": $_app,
    "./routes/api/claim-status.ts": $api_claim_status,
    "./routes/api/claim.ts": $api_claim,
    "./routes/api/ethos-score.ts": $api_ethos_score,
    "./routes/api/ethos-users.ts": $api_ethos_users,
    "./routes/api/search-users.ts": $api_search_users,
    "./routes/api/sync-whitelist.ts": $api_sync_whitelist,
    "./routes/api/transfers.ts": $api_transfers,
    "./routes/api/vouched-users.ts": $api_vouched_users,
    "./routes/index.tsx": $index,
  },
  islands: {
    "./islands/ClaimReward.tsx": $ClaimReward,
    "./islands/ConnectWallet.tsx": $ConnectWallet,
    "./islands/EthosStatus.tsx": $EthosStatus,
    "./islands/Header.tsx": $Header,
    "./islands/HomePage.tsx": $HomePage,
    "./islands/SendTokens.tsx": $SendTokens,
    "./islands/TransactionLog.tsx": $TransactionLog,
    "./islands/VouchedUsers.tsx": $VouchedUsers,
    "./islands/WalletBalance.tsx": $WalletBalance,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
